### ISSUE TITLE
How to merge severals cells?

### ISSUE THREAD

**Issue by ArystanK** [evanrupert/ExcelKt#6]
How to merge severals cells?

**Comment by evanrupert** [comment]
ExcelKt doesn't have a declarative way to do this yet.  But you can use the xssfSheet variable in the sheet builder to use the `addMergedRegion` function from Apache POI.

For example:
```kotlin
    workbook {
        sheet {
            // Merge from row 0, to row 0, from column 0, to column 1
            xssfSheet.addMergedRegion(CellRangeAddress(0, 0, 0, 1))

            row {
                cell("Hello, World")
            }
        }
    }.write("test.xlsx")

```
This will merge the first and second columns in the first row, then write "Hello, World" in it.

Check out the Apache POI documentation for more info about this function: https://poi.apache.org/apidocs/5.0/org/apache/poi/xssf/usermodel/XSSFSheet.html#addMergedRegion-org.apache.poi.ss.util.CellRangeAddress-

**Comment by baggio1103** [comment]
When you call 
```
                xssfSheet.autoSizeColumn(1)
                xssfSheet.autoSizeColumn(2)
                xssfSheet.autoSizeColumn(3)
```
it enters an infinitive loop and never comes out of this loop
I suppose it is a horrible bug
