### ISSUE TITLE
How to set horizontally center for cell

### ISSUE THREAD

**Issue by Tolegen99** [evanrupert/ExcelKt#9]
Hi! This is great lib, thx for it! Can You help me with centering text by horizontal in cell?

**Comment by evanrupert** [comment]
Hi,

My apologies for the late reply, I have had a lot going on.

Horizontal centering can be done by setting the `alignment` property of a cell style to one of the values in the HorizontalAlignment enumeration.

For example, the following code would produce a row where all cells are center aligned.

```kotlin
workbook {
    sheet {
        val centerAligned = createCellStyle {
            alignment = HorizontalAlignment.CENTER
        }

        row(centerAligned) {
            cell("Cell 1")
            cell("Cell 2")
        }
    }
}.write("file.xlsx")
```

[Here](https://poi.apache.org/apidocs/3.17/index.html?org/apache/poi/ss/usermodel/HorizontalAlignment.html) are the docs for Apache POI HorizontalAlignment which displays all the options.

My apologies again for being so late with this.
